Components
Spring-Chatbot/psych_chat pull request #5
Opened 2020-04-14 05:43 UTC by RLewis627

Added all react components (src/components)
Added user-defined CSS (src/css)
Deleted items that are no longer needed (logos, icons, react-native CSS)
Added build folder with contents of `npm build`
Changed App.tsx to accommodate a multi-page web app with HashRouter

2020-04-14 23:31 UTC, Nicholas-Baron requested changes
I strongly recommend removing the build folder from this commit. It is unnecessary and just bloats the repository.
When the pull request merges, I will begin writing the tests in Typescript and will convert the files to Typescript.

2020-04-14 23:31 UTC, Nicholas-Baron commented on src/components/Thanks.js
> +}
Could this be rewritten as a function?
```
export default function Thanks(){
  return ... ;
}
```

2020-04-14 23:31 UTC, Nicholas-Baron commented on src/components/UserLoginBox.js
> +      var Loginpin = document.getElementById("LoginPIN").value;
Could these be `let` or even `const`?

2020-04-14 23:31 UTC, Nicholas-Baron commented on src/components/Register.js
> +        var pin = document.getElementById("pin").value;
Could these be `let` or `const`?

2020-04-14 23:31 UTC, Nicholas-Baron commented on src/components/Conversation.js
> +        var UserComment = document.getElementById("ConvoUserInput").value;
Could this be `let` or `const`?

2020-04-14 23:31 UTC, Nicholas-Baron commented on package.json
> +    "reactstrap": "^8.4.1",
I'll allow it, but please limit the usage of this package.

2020-04-17 06:08 UTC, RLewis627 commented
- Also removed build folder
- Attempted to remove jquery dependency as well, but converting the 2 Jquery functions that exist in Conversation.js to their Javascript counterparts resolves to various errors in the console.
- Attempted to convert files to tsx but it resolves to a large amount of errors that I don't really know how to fix.

2020-04-17 06:11 UTC, Nicholas-Baron commented on src/components/Conversation.js
> +        super(props);
The props are unused. I will rewrite the class as a functional component.

2020-04-17 06:12 UTC, Nicholas-Baron approved these changes
I will begin rewriting the class style components into function style components and adding tests.

2020-04-17 06:12 UTC, merged